### ISSUE TITLE
TWI Pins

### ISSUE THREAD

**Issue by richardseftonTNP** [microchip-pic-avr-examples/attiny1627-bare-metal-twi-mplab#2]
There seems to be a few inconsistencies in this repo

The Readme says PA1 and PA2 are the TWI pins. 

The host.c looks like its setting up PB1 and PB2 as outputs. 

The ATTiny1627 [Data Sheet](https://ww1.microchip.com/downloads/aemDocuments/documents/MCU08/ProductDocuments/DataSheets/ATtiny1624-26-27-DataSheet-DS40002234B.pdf) says its PB0 and PB1

**Comment by pic-avr-github-admin** [comment]
Hi @richardseftonTNP ,
Thanks for your input! You are correct, the right pins are PB0 and PB1. We're working on a README and a bug fix that should be out in a day or so for this example.
